###
POST http://localhost:5600/api/v1/superheroes/superheroe HTTP/1.1
Content-Type: application/json

{
  "real_name": "Santiago",
  "super_name": "Zapata",
  "power": "Fuerza",
  "city": "Bogota"
}

###
GET http://localhost:5600/api/v1/superheroes/ HTTP/1.1

###
GET http://localhost:5600/api/v1/superheroes/638143987b5b4b9cf08099b2 HTTP/1.1

###
PUT http://localhost:5600/api/v1/superheroes/638143987b5b4b9cf08099b2 HTTP/1.1
Content-Type: application/json

{
  "real_name": "Fernando",
  "super_name": "Zapata",
  "power": "Lava",
  "city": "Manizales"
}

###
DELETE http://localhost:5600/api/v1/superheroes/638143987b5b4b9cf08099b2 HTTP/1.1